sudo: required
services:
  - docker

if: commit_message !~ /(no-ci|wip)/

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:

script:
  # build docker images
  - docker build -t chotuve-web-front .
  - docker tag chotuve-web-front registry.heroku.com/$HEROKU_WEB_APP_NAME/web
  # should I do some kind of test here?

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push santiagomariani/chotuve-web-front;
    docker push registry.heroku.com/$HEROKU_WEB_APP_NAME/web;
    heroku container:release web --app $HEROKU_WEB_APP_NAME
  on:
    branch: master
