version: "3.7"

services:
  web:
    container_name: chotuve-web
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ".:/data/app/"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
