# pull official base image
FROM node:12.18.0-alpine3.9

WORKDIR /data/

COPY package*.json /data/

RUN npm cache clean --force
RUN npm install

ENV PATH /data/node_modules/.bin:$PATH

COPY . /data/app/

WORKDIR /data/app/

ENV REACT_APP_API_URL https://chotuve-auth-server-10-staging.herokuapp.com
ENV REACT_APP_USING_FAKE_API ''

# start app
CMD ["sh", "/data/app/docker-entrypoint.sh"]