# pull official base image
FROM node:12.18.0-alpine3.9

WORKDIR /data/

COPY package*.json /data/

RUN npm cache clean --force
RUN npm install

ENV PATH /data/node_modules/.bin:$PATH

COPY . /data/app/

WORKDIR /data/app/

# start app
CMD ["sh", "/data/app/docker-entrypoint.sh"]